/**
 * Captures a REAL /api/sync response and writes it where the Flutter test
 * suite can pick it up, so the Dart decryptor is verified against bytes the
 * actual Node server produced — not against a second Node reimplementation.
 *
 *   node scripts/make-fixture.mjs
 *
 * The fixture holds the live SYNC_SECRET, so it is git-ignored.
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";

const BASE = process.env.BASE ?? "http://127.0.0.1:3000";
const OUT = new URL("../../mobile/test/fixtures/", import.meta.url);

const env = Object.fromEntries(
  readFileSync(new URL("../.env.local", import.meta.url), "utf8")
    .split(/\r?\n/)
    .filter((l) => l.trim() && !l.trim().startsWith("#"))
    .map((l) => {
      const i = l.indexOf("=");
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
    }),
);

const SSID = `__fixture_${Date.now().toString(36)}`;
const PASSWORD = "fixture-password-9182";

const login = await fetch(`${BASE}/api/login`, {
  method: "POST",
  headers: { "content-type": "application/json" },
  body: JSON.stringify({
    username: env.ADMIN_USERNAME,
    password: env.ADMIN_PASSWORD,
  }),
});
if (!login.ok) throw new Error(`login failed: ${login.status}`);
const cookie = (login.headers.get("set-cookie") ?? "").split(";")[0];

const created = await fetch(`${BASE}/api/networks`, {
  method: "POST",
  headers: { "content-type": "application/json", cookie },
  body: JSON.stringify({
    name: "Fixture Net",
    ssid: SSID,
    password: PASSWORD,
    security: "WPA",
    area: "Dhaka",
    note: "generated by make-fixture.mjs",
  }),
});
const id = (await created.json())?.network?.id;
if (!id) throw new Error("could not create fixture network");

try {
  const res = await fetch(`${BASE}/api/sync`, {
    headers: { "x-client-key": env.SYNC_CLIENT_KEY },
  });
  const payload = await res.json();

  mkdirSync(OUT, { recursive: true });
  writeFileSync(
    new URL("server_payload.json", OUT),
    JSON.stringify(
      {
        note: "Real /api/sync response. Regenerate with admin-web/scripts/make-fixture.mjs",
        secret: env.SYNC_SECRET,
        data: payload.data,
        rev: payload.rev,
        expectSsid: SSID,
        expectPassword: PASSWORD,
      },
      null,
      2,
    ),
  );
  console.log(`Wrote fixture for SSID ${SSID} (${payload.count} network(s))`);
} finally {
  await fetch(`${BASE}/api/networks/${id}`, { method: "DELETE", headers: { cookie } });
  console.log("Temp network removed from Supabase.");
}
